# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --deployment

      - run: gem pristine json --version 2.2.0
      # run tests!
      - run:
          name: archive dependencies
          command: |
            zip -r dependencies.zip ./vendor

      - store_artifacts:
          path: dependencies.zip
          destination: vendor